name: get-iplayer
version: master
summary: A utility for downloading TV and radio from BBC iPlayer
description: BBC iPlayer Indexing Tool and PVR
confinement: devmode
grade: devel
apps:
  get-iplayer:
    command: scripts/run-cli.sh
  server:
    command: scripts/run-server.sh
    daemon: simple
parts:
  get-iplayer:
    source: https://github.com/get-iplayer/get_iplayer.git
    plugin: dump
    stage-packages:
      - perl-base
      - libwww-perl
      - liblwp-protocol-https-perl
      - libmojolicious-perl
      - libxml-simple-perl
      - libxml-libxml-perl
      - libcgi-pm-perl
      - atomicparsley
      - ffmpeg
  launcher:
    plugin: dump
    source: .
    organize:
      run-cli.sh: scripts/run-cli.sh
      run-server.sh: scripts/run-server.sh