name: neofetch
version: 3.1.0
summary: Neofetch
description: A fast, highly customizable system info script
confinement: devmode
grade: stable
apps:
  neofetch:
    command: neofetch
parts:
  neofetch:
    plugin: dump
    stage-packages:
      - w3m
      - imagemagick
      - cmus
      - feh
      - mpc
      - nitrogen
      - scrot
      - x11-utils
      - moc
    source: https://github.com/dylanaraps/neofetch.git
    source-tag: 3.1.0
